name: PR QA Automation

on:
  pull_request:
    types: [opened, synchronize]
    branches:
        - main

jobs:
    pr_qa_automation:
        permissions:
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Send data to Dify and get result file
              id: dify_request
              run: |
                pr_summary='${{ github.event.pull_request.body }}'
                pr_number='${{ github.event.pull_request.number }}'

                json_data=$(jq -n \
                    --arg query "$pr_summary" \
                    --arg user "$pr_number" \
                    '{
                        inputs: {},
                        query: $query,
                        response_mode: "blocking",
                        conversation_id: "",
                        user: $user,
                        files: []
                    }')

                response=$(curl -X POST 'https://api.dify.ai/v1/chat-messages' \
                    --header 'Authorization: Bearer ${{ secrets.DIFY_QA_AUTOMATION }}' \
                    --header 'Content-Type: application/json' \
                    --data-raw "$json_data"
                )

                response_body=$(echo "$response" | sed '$d')
                answer=$(echo "$response_body" | jq -r '.answer // empty')
                
                echo "$answer"
                
                echo "csv_text<<EOF" >> $GITHUB_OUTPUT
                echo "$answer" >> $GITHUB_OUTPUT
                echo "EOF" >> $GITHUB_OUTPUT
            - name: Create csv file
              run: |
                echo "${{ steps.dify_request.outputs.csv_text }}"
                echo "${{ steps.dify_request.outputs.csv_text }}" > test_case.csv
            - name: Upload csv file as artifact
              id: uploader
              uses: actions/upload-artifact@v4
              with:
                name: test_case
                path: test_case.csv
            - name: Update PR description with download link
              uses: actions/github-script@v7
              with:
                script: |                  
                  let body = context.payload.pull_request.body;
                  body += '\n\n---\n\n';
                  body += '## QA Test Case\n';
                  body += '[Test Case CSV](${{ steps.uploader.outputs.artifact-url }})';

                  await github.rest.pulls.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: context.payload.pull_request.number,
                    body: body
                  });